### ISSUE TITLE
Guest can check Terms of use

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-ext-tou#1]
Die Gast-Nutzer können auch die ToU bestätigen, das sollte so nicht sein.

Beim Aufruf von: `app.php/tou/`

**Comment by gn36** [comment]
Aber nur wenn sie die Seite direkt aufrufen, oder? Gezwungen werden sie nicht dazu.

**Comment by Crizz0** [comment]
Ja, aber auch das ist eher nicht so Absicht von dir gewesen, oder?

**Comment by gn36** [comment]
Stimmt wohl, ein is_registered check kann wohl nicht schaden.
