### ISSUE TITLE
Uncheck nach Bestätigung der ToU möglich

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-ext-tou#2]
Wenn man die ToU bestätigt kann, kann man die Seite erneut aufrufen und wieder einen "Uncheck" durchführen.

**Comment by gn36** [comment]
Hm das ist natürlich ungünstig. Den Seitenaufruf würde ich nicht verbieten, aber die bestätigungsbuttons sollten wir wohl ausblenden.
