### ISSUE TITLE
Some bbcodes destroys the text output

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-ext-tou#27]
This will lead to: 
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbde/tou/event/main.php on line 212: sprintf(): Too few arguments` with not text output. 

If changed Line 212 to:
`	'AGREEMENT_TEXT'	=> $tou_custom_pp_text,`
the warning is gone, the text is there but only partly parsed. 

E.g.: http://phpbb33.crizzo.de/ucp.php?mode=terms

**Comment by Crizz0** [comment]
@JoshyPHP
Is there a limitation through the s9e text-formatter? 

or something special i need to do?

**Comment by JoshyPHP** [comment]
I don't know, how is it related to the library? I don't see any mention of it on this page.

Looking at the code, you should debug it normally by looking into `$tou_custom_pp_text` with `var_dump($tou_custom_pp_text)` and go from there.

**Comment by Crizz0** [comment]
I think the problem is this line: https://github.com/phpbb/phpbb/blob/2c2414045248fcc98e566f9738290caf9a9038bd/phpBB/styles/prosilver/template/ucp_agreement.html#L65 So the `<p>` element acts strange, when i put in my content other elements like `<ul>` or `<ol>` or `<h2>`, the browser closed it right before. So the parser runs fine. 

Using:
`'AGREEMENT_TEXT'    => '</p><div style="font-size: 120%">' . $tou_custom_tou_text . '</div><p>',`

Instead of 
`'AGREEMENT_TEXT'    => $tou_custom_tou_text,`

is helping there, but really ugly. :/

**Comment by JoshyPHP** [comment]
Yes, that's not related to BBCodes or my library but what you're describing is due to the way browsers are mandated to handle optional tags in HTML. Some elements such as `ul` or `ol` will automatically close the preceding paragraph.

You can find the whole list there: https://www.w3.org/TR/html53/syntax.html#ref-for-elementdef-p%E2%91%A3%E2%91%A0

**Comment by Crizz0** [comment]
k, thx. Sorry for bothering you.

**Comment by JoshyPHP** [comment]
No worries, feel free to tag me on that kind of stuff.
